---
name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron: '0 5 * * *'

jobs:
  alpine:
    name: alpine latest
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: pre-checkout setup
        run: |
          apk add --no-cache \
            ca-certificates \
            git
        shell: sh
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup apk
        run: |
          apk add --no-cache \
            bash \
            curl \
            icu \
            lttng-ust \
            zlib
        shell: sh
      - name: post-checkout setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: build package debug
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Debug --nologo RVOCS.sln
          dotnet pack --configuration Debug --no-build --nologo src/RVOCS.csproj
        shell: sh
      - name: build package release
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Release --nologo RVOCS.sln
          dotnet pack --configuration Release --no-build --nologo src/RVOCS.csproj
        shell: sh

  arch:
    name: arch latest
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: pre-checkout setup
        run: |
          pacman --noconfirm -S -u -y
          pacman --noconfirm -S \
            ca-certificates \
            git
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup pacman
        run: |
          pacman --noconfirm -S -y \
            curl \
            icu \
            lttng-ust \
            zlib
          rm -rf \
            /var/cache/pacman/pkg/* \
            /var/lib/pacman/sync/*
        shell: bash
      - name: post-checkout setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: build package debug
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Debug --nologo RVOCS.sln
          dotnet pack --configuration Debug --no-build --nologo src/RVOCS.csproj
        shell: bash
      - name: build package release
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Release --nologo RVOCS.sln
          dotnet pack --configuration Release --no-build --nologo src/RVOCS.csproj
        shell: bash

  centos:
    name: centos latest
    runs-on: ubuntu-latest
    container: centos:latest
    steps:
      - name: pre-checkout setup
        run: |
          dnf install -q -y \
            ca-certificates \
            glibc-langpack-en \
            git
          rm -rf /var/cache/yum
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup dnf
        run: |
          dnf install -q -y \
            curl \
            libicu \
            lttng-ust \
            zlib
          rm -rf /var/cache/yum
        shell: bash
      - name: post-checkout setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: build package debug
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Debug --nologo RVOCS.sln
          dotnet pack --configuration Debug --no-build --nologo src/RVOCS.csproj
        shell: bash
      - name: build package release
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Release --nologo RVOCS.sln
          dotnet pack --configuration Release --no-build --nologo src/RVOCS.csproj
        shell: bash

  macos:
    name: macos latest
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: build package debug
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Debug --nologo RVOCS.sln
          dotnet pack --configuration Debug --no-build --nologo src/RVOCS.csproj
        shell: zsh -efuo pipefail {0}
      - name: build and pack release
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Release --nologo RVOCS.sln
          dotnet pack --configuration Release --no-build --nologo src/RVOCS.csproj
        shell: zsh -efuo pipefail {0}

  ubuntu:
    name: ubuntu latest
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - name: pre-checkout setup
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            ca-certificates \
            git
          rm -rf /var/lib/apt/lists/*
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: post-checkout setup apt
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update -qq
          apt-get install -o Dpkg::Use-Pty=0 -qq --no-install-recommends \
            curl \
            libicu66 \
            liblttng-ust0 \
            zlib1g
          rm -rf /var/lib/apt/lists/*
      - name: post-checkout setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          source-url: https://nuget.pkg.github.com/snape/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: build package debug
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Debug --nologo RVOCS.sln
          dotnet pack --configuration Debug --no-build --nologo src/RVOCS.csproj
        shell: bash
      - name: build package release
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet build --configuration Release --nologo RVOCS.sln
          dotnet pack --configuration Release --no-build --nologo src/RVOCS.csproj
      - name: push
        run: |
          export DOTNET_CLI_TELEMETRY_OPTOUT=1
          dotnet nuget push --no-symbols true --skip-duplicate src/bin/Release/RVOCS.*.nupkg
        if: ${{ github.event.release.published }}
        shell: bash

  windows:
    name: windows latest
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: build package debug
        run: |
          $Env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
          dotnet build --configuration Debug RVOCS.sln
          dotnet pack --configuration Debug --no-build src\RVOCS.csproj
        shell: powershell
      - name: build and pack release
        run: |
          $Env:DOTNET_CLI_TELEMETRY_OPTOUT = 1
          dotnet build --configuration Release RVOCS.sln
          dotnet pack --configuration Release --no-build src\RVOCS.csproj
        shell: powershell
